import express from "express";
import { errorHandlerMiddleware } from "./middlewares/error-handler";
import { RegisterVehicleController } from "./controllers/register-vehicle-controller";
import { updateVehicleController } from "./controllers/update-vehicle-controller";
import { getVehicleController } from "./controllers/get-vehicle-controller";
import { deleteVehicleController } from "./controllers/delete-vehicle-controller";
import { getManyVehiclesController } from "./controllers/get-many-vehicles-controller";
import { registerDriverController } from "./controllers/register-driver-controller";
import { getDriverController } from "./controllers/get-driver-controller";
import { updateDriverController } from "./controllers/update-driver-controller";
import { deleteDriverController } from "./controllers/delete-driver-controller";
import { getManyDriversController } from "./controllers/get-many-drivers-controller";
import { startRideController } from "./controllers/start-ride-controller";
import { endRideController } from "./controllers/end-ride-controller";
import { getManyRidesEnrichedWithDriverAndVehicleController } from "./controllers/get-many-rides-enriched-with-driver-and-vehicle-controller";

export const expressServer = express();
expressServer.use(express.json());
expressServer.post("/vehicle", RegisterVehicleController);
expressServer.get("/vehicle", getManyVehiclesController);
expressServer.get("/vehicle/:vehicleId", getVehicleController);
expressServer.put("/vehicle/:vehicleId", updateVehicleController);
expressServer.delete("/vehicle/:vehicleId", deleteVehicleController);
expressServer.post("/driver", registerDriverController);
expressServer.get("/driver", getManyDriversController);
expressServer.get("/driver/:driverId", getDriverController);
expressServer.put("/driver/:driverId", updateDriverController);
expressServer.delete("/driver/:driverId", deleteDriverController);
expressServer.post("/ride", startRideController);
expressServer.get("/ride", getManyRidesEnrichedWithDriverAndVehicleController);
expressServer.patch("/ride/:rideId/end", endRideController);
expressServer.use(errorHandlerMiddleware);
